### PR TITLE
Updated Resources Links

### PR DESCRIPTION
**Pull request by tajmone**
Added some more resources/links.

NOTE: original Markdown formatting changed (to Pandoc+GitHub standard
output) due to editor auto-cleanup. Sorry about that...

### CODE REVIEW

**Comment by tajmone** [comment]
I apoligise for the markdown auto-reformatting ... my MD editor auto-cleans up whenever I save.

I know that MD diffing can be a bit of a nightmare, but since I've only added links (and changed 2 entries — Inform and TADS) if the Pandoc default formatting is not a problem I guess you could accept it as is.

Else, we could agree on some standard formatting — invoking pandoc (with agreed upon extensions) to process from markdown to markdown, so that the README file is always formatted according to a given standard.

I was about to create my own Awesome Interactive Fiction list, and when I checked if there was already one in place I was really glad to find yours. I hope we can work on it together!

Best regards

**Comment by tajmone** [comment]
Another commit followed:

I've added more resources links, and also changed/added some categories. Corrected some broken links.

"`Frameworks and Tools`" renamed to "`Software`" -> "`IF Developement Tools`"

"`Interpreters`" now falls under "`Software`", and I've subdivided terps by OS type. Also added some description, regarding which story files are supported.

I've fixed some links which contained twice "`http://`" and were broken...

Hope these structural changes are welcomed.

PS: Is this list intended to be a "curated" list (Awesome-stuff only) or an omni-comprehensive one (link all resources available)?

**Comment by yakiradixon** [comment]
Hey hey,

I'm not bothered by the Markdown formatting change in this case. It's fine.

I like the category changes. I think a couple of the links are still broken, but I'm going to merge this in as-is.

When I started this list, I leaned towards making it a comprehensive one. I still feel the same. However, I'd love to explicitly indicate which resources are thoroughly awesome. 

Thanks for contributing!

**Comment by tajmone** [comment]
Thanks for merging!

I agree: a comprehensive list suite better the Interactive Fiction vast echo-system — many of the "old systems" are actually still in use (like Z-Code); and since usually story files are played into virtual machines, there is an abundance of implementation for different platforms, all of them worth mentioning.

**Pull request merged**
